language: ruby
cache: bundler
rvm:
  - 2.2.0
before_script:
  - psql -c "CREATE USER serler WITH CREATEUSER PASSWORD 'serler';" -U postgres
  - psql -c "ALTER USER serler CREATEDB;" -U postgres
  - psql -c 'create database serler_test_db OWNER serler' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start -extension RANDR"
  - sleep 3 # give xvfb some time to start
  - echo $PATH
  - pwd
  - bundle exec rails server -d -e test  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
  - curl http://localhost:3000/search_fields/list.json
  - firefox http://localhost:3000 &
script:
  - RAILS_ENV=test rake db:migrate
  - RAILS_ENV=test rake db:seed
  - RAILS_ENV=test rake	test
  - RAILS_ENV=test rake spec
  - RAILS_ENV=test rake	cucumber
  