# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  # create a local PostgreSQL database, and update the following entry to your name
  database: serler_dev_db
  username: maochuanli
  # by default, there is no password for the database account, but in case you have, update this entry
  #password:

  host: localhost
  port: 5432

test:
  <<: *default
  database: serler_test_db

production:
  <<: *default
  # before using the following environment variable, set it on heroku command line: 
  # heroku config:set DATABASE_URL=postgres://xvmfnuybptqfiv:x1a6JSbvzFr56u7-GjHo9_Hqpg@ec2-54-204-3-188.compute-1.amazonaws.com:5432/d93fe......
  # this can also be set from the heroku web page: Application -> Settings -> Config Variables -> EDIT
  # the database URL could be retrieved from: Dashboard -> Databases -> <Your DB> -> URL -> Show
  url: <%= ENV['DATABASE_URL'] %>

