# Make sure the following 2 databases are created owned by the user: serler
# > sudo -s -u  postgres
# > psql
# > postgres=# CREATE USER serler WITH PASSWORD 'serler';
# > postgres=# CREATE DATABASE serler_dev_db OWNER serler;
# > postgres=# CREATE DATABASE serler_test_db OWNER serler;

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: serler
  password: serler
  host: localhost
  port: 5432

development:
  <<: *default
  database: serler_dev_db

test:
  <<: *default
  database: serler_test_db

production:
  <<: *default
  # before using the following environment variable, set it on heroku command line: 
  # heroku config:set DATABASE_URL=postgres://xvmfnuybptqfiv:x1a6JSbvzFr56u7-GjHo9_Hqpg@ec2-54-204-3-188.compute-1.amazonaws.com:5432/d93fe......
  # this can also be set from the heroku web page: Application -> Settings -> Config Variables -> EDIT
  # the database URL could be retrieved from: Dashboard -> Databases -> <Your DB> -> URL -> Show
  url: <%= ENV['DATABASE_URL'] %>

